### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by anaskhan96** [serendipious/nodejs-decision-tree-id3#14]
How does this algorithm handle cases of missing data in the dataset?

**Comment by drferreira** [comment]
Great question!

**Comment by serendipious** [comment]
Hey Anas, Great Question! ID3 treats the missing value as another category and uses it for splitting. Current approaches (to the best of my knowledge) however dictate distributing data points with missing values to child nodes during training, and not using them when evaluating a split.

**Comment by anaskhan96** [comment]
This does answer my question. I just had doubts concerning what approach this module was taking when it came across missing data.
