### ISSUE TITLE
The package don't allow import the model already trained

### ISSUE THREAD

**Issue by rcaceiro** [serendipious/nodejs-decision-tree-id3#16]
We cannot load one model already trained. A cool feature is to import a already trained model.

**Comment by serendipious** [comment]
@rcaceiro Hey Rúben, Thanks for the suggestion! I've added a feature to allow initializing a tree with a previously trained model (see usage below). Hope that matches the feature you're describing! 🤞😊

```javascript
var treeJson = dt.toJSON();
var preTrainedDecisionTree = new DecisionTree(treeJson);
```
