### ISSUE TITLE
Subsequent declarations screw up the previous models

### ISSUE THREAD

**Issue by mysticaltech** [serendipious/nodejs-decision-tree-id3#21]
Hello, when I have 1 model, it works great (dynamic_dt below predicts correctly), but when I declare multiple ones (dynamic_dt, mde_dt, ...etc) the results are not accurate. What is happening here, how can I fix this?

![Screen Shot 2021-02-08 at 6 51 48 PM](https://user-images.githubusercontent.com/518555/107260879-e6f0f600-6a3e-11eb-8598-860c80e780ac.png)

**Comment by serendipious** [comment]
Sorry for the delayed response @mysticaltech, and thanks for filing this bug. I was able to locate the issue in a shared variable used, that is now fixed in the latest release (>= 0.3.4). Feel free to re-open if I missed anything. Thanks!
