### ISSUE TITLE
Build de tree

### ISSUE THREAD

**Issue by carlos-cabgj** [serendipious/nodejs-decision-tree-id3#24]
Hi, I would like to know how can I build a  visual representation of tree.
I saw how to predict but I can't understand how can I build the tree.

**Comment by serendipious** [comment]
Hi Carlos, You can use the this method to get the underlying JSON representation of the decision tree to build your visualization. Hope that helps!

https://github.com/serendipious/nodejs-decision-tree-id3#export-underlying-model-for-visualization-or-inspection

**Comment by carlos-cabgj** [comment]
Thank you, I was stalled in the example, but looking better, model.vals can bring the whole information that I need!
